name: Deploy Indexer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /home/kizovps/kizo/indexer
          
          echo "🔄 Pulling latest changes..."
          git pull origin main || git pull origin master
          
          echo "📊 Building indexer Docker image..."
          sudo docker build -t kizo-indexer:latest .
          
          echo "🔄 Stopping old container..."
          sudo docker stop kizo-indexer || true
          sudo docker rm kizo-indexer || true
          
          echo "🚀 Starting new container..."
          sudo docker run -d \
            --name kizo-indexer \
            --network host \
            --restart unless-stopped \
            kizo-indexer:latest
          
          echo "🧹 Cleaning up old images..."
          sudo docker image prune -f
          
          echo "✅ Indexer deployment completed!"
          sudo docker ps | grep kizo-indexer
